### PR TITLE
feat: add DocSearch as recommended by vuepress

### PR DESCRIPTION
**Pull request by s-pace**
👋 team,

I am working on DocSearch. [We have an integration for Vuepress](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search). We thought it is a shame you can not also used this search that you can [find on vuejs for example](https://vuejs.org/).

This PR will add DocSearch to the documentation website. It will allow a user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

Let me know if you need anything.

### CODE REVIEW

**Comment by ayrc** [comment]
Hi Sylvain,

Thank you for your PR! We currently need to make some infrastructural updates to our documentation, so we'll keep this in mind when we get around to it.

**Comment by amzn-chris-subagio** [comment]
@s-pace Hey, we just upgraded our VuePress dependency to current. Would the doc search integration you suggested still be valid now? Doc search seems like a great addition to the site.

**Comment by s-pace** [comment]
All good now, I have updated the configuration and you should be ready to go :)

**Comment by amzn-chris-subagio** [comment]
Thanks! Looking forward to trying it : )

**Pull request merged**
